package Producto;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import java.awt.Frame;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class Producto_men extends javax.swing.JPanel {
    private ProductoDAO productoDAO = new ProductoDAO();
    
    /**
     * Creates new form CategoriaForm
     */
    public Producto_men() {
        initComponents();
        
        // Cargar datos a la tabla del formulario
        cargarDatos();
    }
    
    private void cargarDatos() {
        DefaultTableModel modelo = (DefaultTableModel) jtContenido.getModel();
        modelo.setRowCount(0);
        
        //System.out.println("-->> "+productoDAO.listar().size());
        for (Producto c : productoDAO.listar()) { // ← modelo.Categoria
            modelo.addRow(new Object[]{c.getId(), c.getNombre()});
        }
        ajustarAnchoColumnas();
    }
    private void ajustarAnchoColumnas() {
        // Obtener el modelo de columnas
        TableColumnModel columnModel = jtContenido.getColumnModel();

        // Columna 0: ID → ancho pequeño
        columnModel.getColumn(0).setPreferredWidth(50);   // ID
        columnModel.getColumn(0).setMinWidth(50);
        columnModel.getColumn(0).setMaxWidth(80);
        
//        // Columna 1: Nombre → más ancha
//        columnModel.getColumn(1).setPreferredWidth(200);
//        columnModel.getColumn(1).setMinWidth(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtContenido = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Precio compra", "Precio venta", "Categoría", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtContenido.setToolTipText("");
        jScrollPane1.setViewportView(jtContenido);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // 1. Obtener ventana padre
        Window window = SwingUtilities.getWindowAncestor(this);
        if (!(window instanceof Frame)) {
            JOptionPane.showMessageDialog(this, "No se puede abrir el formulario.");
            return;
        }
        
        // 2. Crear y mostrar el diálogo
        ProductoForm dialog = new ProductoForm((Frame) window, true);
        dialog.setVisible(true); // bloquea hasta que se cierre
        
        // 3. Después de cerrar, verificar si se guardó
        if (dialog.isGuardado()) {
            String nombre = dialog.getNombreIngresado();
            
            JOptionPane.showMessageDialog(this, "nombre: " + nombre);
            
//            // 4. Usar el DAO para insertar
//            if (categoriaDAO.insertar(nombre)) {
//                JOptionPane.showMessageDialog(this, "✅ Producto agregado con éxito.");
//                cargarDatos(); // refresca el JTable
//            } else {
//                JOptionPane.showMessageDialog(this, "❌ Error al guardar en la base de datos.");
//            }
        }
        // Si fue cancelado, no hace nada
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // 1. Verificar fila seleccionada
        int filaSeleccionada = jtContenido.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un Producto para editar.");
            return;
        }
        
        // 2. Obtener datos
        Integer id = (Integer) jtContenido.getValueAt(filaSeleccionada, 0);
        String nombre = (String) jtContenido.getValueAt(filaSeleccionada, 1);

        // 3. Obtener ventana padre
        Window window = SwingUtilities.getWindowAncestor(this);
        if (!(window instanceof Frame)) {
            JOptionPane.showMessageDialog(this, "No se puede abrir el diálogo.");
            return;
        }
        
        // 4. Abrir el diálogo en modo edición
        var dialog = new ProductoForm((Frame) window, true, id, nombre);
        dialog.setVisible(true); // bloquea hasta que se cierre

        // 5. Si se guardó, actualizar en BD y en tabla
        if (dialog.isGuardado()) {
            String nuevoNombre = dialog.getNombreIngresado();
            
            if (productoDAO.actualizar(id, nuevoNombre)) {
                JOptionPane.showMessageDialog(this, "✅ Categoría actualizada con éxito.");
                cargarDatos(); // refresca el JTable
            } else {
                JOptionPane.showMessageDialog(this, "❌ Error al actualizar en la base de datos.");
            }
            
            // Opcional: actualizar solo esa celda en la tabla
            jtContenido.setValueAt(nuevoNombre, filaSeleccionada, 1);
        }
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtContenido;
    // End of variables declaration//GEN-END:variables
}
